# This role installs and configures Nginx on Ubuntu, deploys a simple HTML page,
# and ensures that the Nginx service is running and enabled to start on boot.

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  tags: nginx

- name: Copy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx
  tags: nginx

- name: Deploy a simple HTML page with VM name
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  tags: nginx

- name: Ensure Nginx is running and enabled on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx
